#pragma once

typedef enum ItemDefinitionIndex : short {
    ItemDefinitionIndex_Deagle = 1,
    ItemDefinitionIndex_Elite,
    ItemDefinitionIndex_Fiveseven,
    ItemDefinitionIndex_Glock,
    ItemDefinitionIndex_Ak47 = 7,
    ItemDefinitionIndex_Aug,
    ItemDefinitionIndex_Awp,
    ItemDefinitionIndex_Famas,
    ItemDefinitionIndex_G3SG1,
    ItemDefinitionIndex_GalilAr = 13,
    ItemDefinitionIndex_M249,
    ItemDefinitionIndex_M4A1 = 16,
    ItemDefinitionIndex_Mac10,
    ItemDefinitionIndex_P90 = 19,
    ItemDefinitionIndex_Mp5sd = 23,
    ItemDefinitionIndex_Ump45,
    ItemDefinitionIndex_Xm1014,
    ItemDefinitionIndex_Bizon,
    ItemDefinitionIndex_Mag7,
    ItemDefinitionIndex_Negev,
    ItemDefinitionIndex_Sawedoff,
    ItemDefinitionIndex_Tec9,
    ItemDefinitionIndex_Taser,
    ItemDefinitionIndex_Hkp2000,
    ItemDefinitionIndex_Mp7,
    ItemDefinitionIndex_Mp9,
    ItemDefinitionIndex_Nova,
    ItemDefinitionIndex_P250,
    ItemDefinitionIndex_Scar20 = 38,
    ItemDefinitionIndex_Sg553,
    ItemDefinitionIndex_Ssg08,
    ItemDefinitionIndex_GoldenKnife,
    ItemDefinitionIndex_M4a1_s = 60,
    ItemDefinitionIndex_Usp_s,
    ItemDefinitionIndex_Cz75a = 63,
    ItemDefinitionIndex_Revolver,
    ItemDefinitionIndex_GhostKnife = 80,
    ItemDefinitionIndex_Bayonet = 500,
    ItemDefinitionIndex_Flip = 505,
    ItemDefinitionIndex_Gut,
    ItemDefinitionIndex_Karambit,
    ItemDefinitionIndex_M9Bayonet,
    ItemDefinitionIndex_Huntsman,
    ItemDefinitionIndex_Falchion = 512,
    ItemDefinitionIndex_Bowie = 514,
    ItemDefinitionIndex_Butterfly,
    ItemDefinitionIndex_Daggers,
    ItemDefinitionIndex_Ursus = 519,
    ItemDefinitionIndex_Navaja,
    ItemDefinitionIndex_Stiletto = 522,
    ItemDefinitionIndex_Talon,
    ItemDefinitionIndex_GloveStuddedBloodhound = 5027,
    ItemDefinitionIndex_GloveT,
    ItemDefinitionIndex_GloveCT,
    ItemDefinitionIndex_GloveSporty,
    ItemDefinitionIndex_GloveSlick,
    ItemDefinitionIndex_GloveLeatherWrap,
    ItemDefinitionIndex_GloveMotorcycle,
    ItemDefinitionIndex_GloveSpecialist,
    ItemDefinitionIndex_GloveHydra
} ItemDefinitionIndex;
